// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD_Bjm6mQ0iOnyB3uUO2846uuuYeCK-vo',
    appId: '1:1089927851162:web:2716a2522a464cde298323',
    messagingSenderId: '1089927851162',
    projectId: 'empowered-dating',
    authDomain: 'empowered-dating.firebaseapp.com',
    storageBucket: 'empowered-dating.appspot.com',
    measurementId: 'G-NM8LE1ZPGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbt8Uw4PNGTPzgt6li4UL1A9v9rclhCzI',
    appId: '1:1089927851162:android:43aae7778588debe298323',
    messagingSenderId: '1089927851162',
    projectId: 'empowered-dating',
    storageBucket: 'empowered-dating.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1ae1o2MYWOM33kEGHoiQtSzmk-ENnNoc',
    appId: '1:1089927851162:ios:0277f0f32acb27e8298323',
    messagingSenderId: '1089927851162',
    projectId: 'empowered-dating',
    storageBucket: 'empowered-dating.appspot.com',
    iosBundleId: 'com.example.empoweredDating',
  );
}
